name: ci-checks

# run on all pull requests and on select branch pushes
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-22.04, r: 'release'}
          - {os: windows-2022, r: 'release'}
    env:
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, any::covr, any::DT, any::devtools
      - name: check package
        uses: r-lib/actions/check-r-package@v2
      # run tests
      - name: Test coverage
        if: runner.os == 'Windows'
        run: |
          devtools::test()
        shell: Rscript {0}
      - name: Test coverage
        if: runner.os == 'Linux'
        run: |
          covr::codecov(
            quiet = FALSE,
            clean = FALSE,
            install_path = file.path(Sys.getenv("RUNNER_TEMP"), "package")
          )
        shell: Rscript {0}
      # fetch coverage outputs
      - name: Show coverage outputs
        if: runner.os == 'Linux'
        run: |
          find ${{ runner.temp }}/package -name 'testthat.Rout*' -exec cat '{}' \; || true
          echo "# Output coverage:" >> $GITHUB_STEP_SUMMARY
          find ${{ runner.temp }}/package -name 'testthat.Rout*' -exec cat '{}' \; || true >> $GITHUB_STEP_SUMMARY
        shell: bash
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: runner.os == 'Linux' && failure()
        with:
          name: rscaffold-coverage
          path: ${{ runner.temp }}/package
          retention-days: 7
