name: ci-checks

# run on all pull requests and on select branch pushes
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '30 3 1 */1 *'  # At 03:30 on the 1st of every month
  workflow_dispatch:

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-22.04, r: 'release'}
          - {os: windows-2022, r: 'release'}
    env:
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, any::covr, any::DT, any::devtools
      - name: Check Package
        uses: r-lib/actions/check-r-package@v2
      - name: Test Coverage
        run: Rscript scripts/coverage.R
      - name: Build documentation
        if: runner.os == 'Linux'
        run: |
          devtools::build_site(preview=F, new_process=F)
          devtools::build(vignettes=T, manual=T, path="dist")
        shell: Rscript {0}
      - name: Upload Interactive Coverage Report
        uses: actions/upload-artifact@v4
        if: runner.os == 'Linux'
        with:
          name: rscaffold
          path: |
            coverage
            docs
            dist
          retention-days: 90
